### ISSUE TITLE
Buttons stop working in generator modes.

### ISSUE THREAD

**Issue by vdgno** [westlicht/performer#214] opened 2020-07-07 09:52 UTC
I have ver 0.1.35. when entering random or euclidian generator from step screen, all sequencer buttons stop to response except function buttons. Definitely a bug here.

**Comment by westlicht** [comment] 2020-07-19 20:33
Not really a bug, the generate page is a modal page, meaning it captures all input. What buttons would you have expected to keep working? Play/stop? Other?

**Comment by vdgno** [comment] 2020-07-20 20:16
At least start stop buttons and the ability to leave generative mode back to normal would be great.

**Comment by westlicht** [comment] 2020-07-20 20:19
You can leave the page by either using _COMMIT_ or _REVERT_ in the context menu (hold `SHIFT` + `PAGE` key).

**Comment by westlicht** [comment] 2020-07-20 20:19
But there is a reason the generators are not yet documented. It's a sort of unfinished feature for a long time now. See #12

**Comment by westlicht** [comment] 2020-07-20 20:21
Closing this, as it's not a bug per se.

**Closed by westlicht** 2020-07-20 20:21 UTC

**Comment by vdgno** [comment] 2020-07-21 06:55
> You can leave the page by either using _COMMIT_ or _REVERT_ in the context menu (hold `SHIFT` + `PAGE` key).

great. thank you
