### ISSUE TITLE
vcv rack plugin

### ISSUE THREAD

**Issue by Noir-** [westlicht/performer#180] opened 2020-03-14 14:25 UTC
What do you think about porting this wonderful sequencer to vcv rack? This could help to grow the user base and maybe attract some developers.

**Comment by westlicht** [comment] 2020-03-21 09:58
I did consider that a long time ago, but I don't think it makes a lot of sense as controlling the sequencer through mouse/keyboard is very tedious.

Duplicate of #24

**Closed by westlicht** 2020-03-21 09:58 UTC
