### ISSUE TITLE
could randomizer hold previous values?

### ISSUE THREAD

**Issue by natedey** [westlicht/performer#265] opened 2020-12-14 00:05 UTC
I go into the COND menu and pick seed 54, smooth 6, offset 3 and commit to randomizing some parameter of the sequence. Then let's say I want to randomize some other parameter with seed 54, smooth 6, offset 3. I have to start from scratch and redial that in. That's a lot of button pushes and wiggles. 
Could the front COND menu have a "redo last params" option, or could the Euclidiean and random generators remember the previous state? (Doesn't have to be persistent after power cycle)
Thanks!

**Comment by westlicht** [comment] 2020-12-16 16:08
I assume this is a duplicate of #255

**Closed by westlicht** 2020-12-16 16:08 UTC
