### ISSUE TITLE
Euclidean bugs

### ISSUE THREAD

**Issue by luisonly** [westlicht/performer#97] opened 2019-07-16 01:50 UTC
Hi :) Loving everything about the seq, and the euclidean generator is amazing for polyrhytms and stuff. Now the problems I have encountered:

1. When I apply a euclidean generator to a track, I lose the routing (in this case midi routing) I had assigned for start and end points in the sequence.

2. If the track is playing 1/32 (or any other division) euclidean generator will change it to 1/16... itd be nice that it sticks to whatever division the track was set to. 

Thank you simon!

**Comment by westlicht** [comment] 2019-07-17 19:10
> 1. When I apply a euclidean generator to a track, I lose the routing (in this case midi routing) I had assigned for start and end points in the sequence.

This is caused by the same issue as #98.

> 2. If the track is playing 1/32 (or any other division) euclidean generator will change it to 1/16... itd be nice that it sticks to whatever division the track was set to.

Good catch, this is because using the euclidean generator actually clears the pattern and resets it to default values. Will change this.

**Comment by westlicht** [comment] 2019-07-18 21:00
Will be fixed with 0.1.25.

**Closed by westlicht** 2019-07-18 21:00 UTC
Labels: bug
